README.md, src/SHA.jl, src/base_functions.jl, src/common.jl, src/constants.jl, src/sha1.jl, src/sha2.jl, src/types.jl, test/perf.jl, test/runtests.jl
@tkelman I was on a train today; which means I had some quality time with my laptop, and some decidedly low-quality internet.  Turns out I could reuse more code than I thought, which was nice!
Performance isn't horrible; try out `julia test/perf.jl <input file>`, but I think I might need to use subarrays in a few places to avoid excessive allocations.  Let me know what you think!  My guess is that [this line](https://github.com/staticfloat/SHA.jl/blob/05ecc992d00dd4841aba9edde408f141462396ce/src/common.jl#L40) is the main culprit:
```
$ ~/src/julia/julia perf.jl ~/Downloads/archlinux-2015.08.01-dual.iso
read:      0.443357 seconds (15 allocations: 657.001 MB)
SHA-1:     7.899572 seconds (43.06 M allocations: 3.048 GB, 1.71% gc time)
SHA-256:  11.636706 seconds (43.06 M allocations: 3.048 …
```
=> Perform fairly big reorganization of code, add in SHA1

README.md, src/SHA.jl, src/base_functions.jl, src/common.jl, src/constants.jl, src/sha2.jl, src/sha3.jl, src/types.jl, test/perf.jl, test/runtests.jl
* shaX_YYY() functions now return bytes instead of strings (Closes https://github.com/staticfloat/SHA.jl/issues/12)
* Cleanup some of the SHA2 functions to be more readable
* First draft of SHA3 algorithm, although it is pretty slow as-is.
=> Fairly big cleanup, SHA3 and bytes instead of strings!

.travis.yml, REQUIRE, src/base_functions.jl, src/common.jl, src/sha1.jl, src/sha2.jl, src/sha3.jl, src/types.jl, test/runtests.jl
`@staticfloat`, `$` is deprecated so here is an update. I've bumped the version requirement so this PR should wait for https://github.com/JuliaLang/METADATA.jl/pull/7038
=> Use ⊻ instead of $ and bump Compat requirement

src/base_functions.jl
Remove final depwarn
`Testing on one million a's (chunked properly)WARNING: map!{F}(f::F, A::AbstractArray) is deprecated, use map!(f, A, A) instead.`
@staticfloat
=> Update dep map! method

REQUIRE, src/types.jl
~~**DO NOT MERGE NOW!!!!**~~
~~This requires https://github.com/JuliaLang/Compat.jl/pull/325 and a new tag. I'm using this (and other) PR's to check if the implementation is correct.~~
Ready now.
=> Fix 0.6 abstract type declaration depwarn

src/common.jl, src/sha1.jl, src/sha2.jl, src/sha3.jl, src/types.jl
This is the simplest and the most local fix I can come up with. If the `buffer` field is not meant to be publically accessed, it is better to use a wider array and reinterpret back to `UInt8` if it needs to be accessed as bytes.
@staticfloat
=> Fix wrong use of reinterpret

.travis.yml, README.md, REQUIRE, src/SHA.jl, src/base_functions.jl, src/common.jl, src/sha1.jl, src/sha2.jl, src/sha3.jl, src/types.jl, test/runtests.jl
Hashing for `NTuple{N, UInt8}`
had to change `Array{UInt8, 1}` to `Array{UInt8, N}` in `sha*` and `update!` for some reason, else I get the following error:
```
ERROR: LoadError: MethodError: no method matching sha1(::Array{UInt8,1})
Closest candidates are:
sha1(::Union{Array{UInt8,1}, Tuple{Vararg{UInt8,N}}}) where N at /home/gkraemer/.julia/v0.6/SHA/src/SHA.jl:42
sha1(!Matched::AbstractString) at /home/gkraemer/.julia/v0.6/SHA/src/SHA.jl:48
sha1(!Matched::IO) at /home/gkraemer/.julia/v0.6/SHA/src/SHA.jl:54
```
=> hashing tuples

src/SHA.jl, src/hmac.jl, test/runtests.jl
This PR adds HMAC functionality by
- an `HMAC_CTX` that has the same `update!` and `digest!` interface with `SHA_CTX`s. It can be instantialized with an `SHA_CTX` and a key.
- convenient methods with prefix `hmac_` which accept a key as the first argument.
- some test cases from [wiki](https://en.wikipedia.org/wiki/Hash-based_message_authentication_code#Examples)
> When opening an issue, please ping `@staticfloat` since he does not receive emails automatically when new issues are created.
=> add HMAC functionalities

src/common.jl
@staticfloat
Abstract Types are more extendable than Unions.
I spotted that this one already existed and wasn't being used.
I believe this covers the same types.
I also believe that I can maybe use this for making `update!(::MD5_CTX)` work.
if so it suggest that a more abstract type  perhaps 
`MerkleDamgård_CTX` (:-P) might be in order,
but that is getting ahead of myself.
For the purposes of SHA.jl, this is just slightly cleaner code
=> =Use abstract type, not union

src/common.jl, src/sha1.jl, src/sha2.jl, src/types.jl
@staticfloat
I have split-up some methods: (I think just) `pad_remainder` from `digest!`
and I have added a some methods: (I think just) `buffer_pointer`
and made a few tweaks.
By doing this I can just call SHA.jl from MD5.jl for a lot of the work.
=> Abstractions for MD5.jl

src/common.jl, src/constants.jl, src/sha3.jl, src/types.jl, test/perf.jl
This makes SHA3 about 3x faster, and the other hash functions moderately faster. The code is a little uglier, but worth it I think!
Hashing a ~400MB file:
**Before**
```
read:      0.169224 seconds (6 allocations: 392.499 MiB, 26.97% gc time)
SHA-1:     1.788647 seconds (7 allocations: 960 bytes)
SHA2-256:   4.946575 seconds (6 allocations: 512 bytes)
SHA2-512:   3.785016 seconds (6 allocations: 656 bytes)
SHA3-256:  15.608980 seconds (3.03 M allocations: 369.411 MiB, 0.02% gc time)
SHA3-512:  29.399319 seconds (5.72 M allocations: 697.775 MiB, 0.02% gc time)
```
**After**
```
read:      0.171445 seconds (6 allocations: 392.499 MiB, 26.98% gc time)
SHA-1:     1.358481 seconds (7 allocations: 960 bytes)
SHA2-256:   4.567648 seconds (6 allocations: 512 bytes)
SHA2-512:   2.906533 seconds (6 …
```
=> Optimize SHA3 implementation.

REQUIRE, src/SHA.jl, src/common.jl, src/hmac.jl
@staticfloat and @KristofferC, this PR allows one to hash data while making fewer copies:
* The type signature of the hashing functions is widened to accept `AbstractVector{UInt8}`
* When hashing a file, a `data[1:num_bytes]` slice copy is eliminated by adding an optional length argument to the internal `update!` function.  (I could have instead used `@views`, but this way I can eliminate the `SubArray` allocation.)
* A `String` is hashed by directly passing `codeunits(str)` (an `AbstractVector{UInt8}` in 0.7) to the hashing function.
Previously, arbitrary `AbstractString` objects were hashed by passing `Vector{UInt8}(codeunits(str))` to the hashing function, but this seemed wrong to me.  Not only does it mean that the hash becomes encoding dependent, but it will fail for something like a …
=> allow AbstractVector{UInt8}, make fewer copies

src/SHA.jl, src/common.jl, src/types.jl, test/runtests.jl
Some development had occured on the copy of SHA that was vendored into
Base Julia.  This merges the changes (mostly documentation) into this
external package, in preparation of moving SHA over to be an "external
stdlib".
=> Bring improvements from `Base` Julia out to `SHA.jl`

test/runtests.jl
As part of making tests less noisy https://github.com/JuliaLang/julia/pull/44444 I saw that this info line always shows in Base tests. Perhaps it could become a debug?
@staticfloat
=> Switch info for debug log

src/common.jl, src/sha3.jl, src/types.jl, test/runtests.jl
Prevent users from calling `update!` on a context that has already been finalized, and warn against doing this in the docstring of `digest!`
If storing a `Bool` in the structs is too wasteful (8-bytes alignment and all), we can use the top bit of the `bytecount` field instead. Let me know if you think this optimisation is worth the additional implementation complexity.
Closes #85
=> Protect against re-using digested context

src/SHA.jl, test/runtests.jl
- `@assert length(key) > blocksize` 
xref: #75
- `@assert usedspace == blocklen(T) - 1`
=> More test - Can we have 100% test coverage?

src/SHA.jl
Hi @staticfloat 
I updated my SHA Pkg and wanted to start using shake. So i noticed, i did a flaw in the export descriptions, which did not match to the function names in the shake.jl and the tests.
But these small changes should fix it. Sorry for the mess.
=> shake128,shake256: fixed typo in export declarations

src/shake.jl, test/runtests.jl
Hi @staticfloat  
@inkydragon  mentioned a bug in some lines missed by the Code-Coverage.
There was a bug in the Padding, which differs from SHA3. 
I added new tests, which covers the lines and changed the padding.
=> Issue #94 (shake128 test coverage): fixed bug in padding for shake, added testcases for full code coverage

README.md, docs/src/index.md, src/common.jl, src/shake.jl, src/types.jl
At least for the docstring and examples this reduces user confusion.
=> Use `Vector` instead of `Array` to simplify types.

src/types.jl
Close #77
I've checked all `SHA2_CTX` and `SHA3_CTX` subtypes usage  by using JuliaHub.
Only a few packages use SHA.jl directly.
All packages use only the exported API.
So it seems safe to remove this code.
To be on the safe side, we could run pkg-eval the next time you update the SHA version in julia.
- https://juliahub.com/ui/Search?q=SHA2_256_CTX&type=symbols
- https://juliahub.com/ui/Search?q=SHA2_512_CTX&type=symbols
- https://juliahub.com/ui/Search?q=SHA256_CTX&type=symbols
=> Remvoe all getproperty funcs

src/types.jl
The same definitions can be found at the top of the file.
@staticfloat
=> rm: Duplicated const alias

.github/workflows/CI.yml, test/runtests.jl
`Base.getproperty` was removed in #99.
With https://github.com/JuliaLang/julia/pull/54504, those tests will fail.
=> test: remove outdate tests

.github/workflows/CI.yml, src/shake.jl
=> Fix type mismatch for `shake` and setup x86 ci

.github/workflows/CI.yml
- test with lts version
- test with `macos-aarch64` * `[lts, nightly]`
- add julia-actions/cache
- add token for codecov/codecov-action
=> ci: Update ci config

test/runtests.jl
These are noisy on Base CI. 
Should both lines just be removed instead? Or are they testing that they don't error?
They were added in https://github.com/JuliaCrypto/SHA.jl/pull/92
```
  | 2025-01-19 15:18:12 EST | From worker 7:	  0.012981 seconds (19 allocations: 98.805 KiB)
  | 2025-01-19 15:18:12 EST | From worker 7:	  0.010351 seconds (19 allocations: 98.867 KiB)
  | 2025-01-19 15:18:12 EST | SHA                                               (7) \|   118.92 \|   0.13 \|  0.1 \|     361.09 \|  1452.17
```
=> remove `@time` from tests
